version: '3.9'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    depends_on:
      - postgres
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JOker1988++++
      POSTGRES_DB: BaseTemplate
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
    command: >
      postgres -c max_connections=5000
               -c max_worker_processes=16
               -c max_parallel_workers=16
               -c max_parallel_workers_per_gather=4
               -c work_mem=64MB
               -c shared_buffers=512MB
               -c maintenance_work_mem=128MB

volumes:
  pg_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
