-- =============================================
-- Create Table: user_role
-- =============================================
CREATE TABLE IF NOT EXISTS user_role (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES app_user(id),
    role VARCHAR(100),
    
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    last_modified TIMESTAMPTZ,
    last_modified_by VARCHAR(100)
);