-- =============================================
-- Create Table: todo_list
-- =============================================
CREATE TABLE IF NOT EXISTS todo_list (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    colour VARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
    
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    last_modified TIMESTAMPTZ,
    last_modified_by VARCHAR(100)
); 